### PR TITLE
Improve documentation quality

### PR DESCRIPTION
**Pull request by JanssenBrm**
While editing the text, I noticed a few issues with how we’re currently writing the documentation:

- Inconsistent styling across markdown pages (indents, spacing, line lengths, etc.)
- Broken links

To address this, I’ve expanded the pre-commit approach by adding two additional steps aimed at tackling these issues. However, since I'm not highly experienced in best practices for this, I’d appreciate your thoughts or any alternative suggestions you might have.

### CODE REVIEW

**Review by jdries — APPROVED** [review]
fine for me, don't have experience with this myself, so can't tell if the changes will work.

**Comment by JanssenBrm** [comment]
@soxofaan  - Do you have any experience with these tools? It would be good if someone could test this from scratch to see if it is working without many hurdles.

**Comment by soxofaan** [comment]
pre-commit is part of my daily workflow nowadays, but I don't know these marakdown linting tools/plugins.

I tried to see what these tools mean on the current state of the repo with `pre-commit run --all-files`  and I think there is quite list of issues we probably fix first before merging this PR (otherwise subsequent commits might be annoying):


```
pre-commit run --all-files
trim trailing whitespace.................................................Passed
fix end of files.........................................................Passed
check for added large files..............................................Passed
check json...........................................(no files to check)Skipped
check yaml...............................................................Passed
check toml...........................................(no files to check)Skipped
pretty format json...................................(no files to check)Skipped
markdownlint.............................................................Failed
- hook id: markdownlint
- exit code: 1

interoperability/algohosting.md:21:121 MD013/line-length Line length [Expected: 120; Actual: 522]
interoperability/algohosting.md:23:121 MD013/line-length Line length [Expected: 120; Actual: 522]
interoperability/algohosting.md:25:121 MD013/line-length Line length [Expected: 120; Actual: 522]
interoperability/algohosting.md:27:121 MD013/line-length Line length [Expected: 120; Actual: 522]
interoperability/algohosting.md:29:121 MD013/line-length Line length [Expected: 120; Actual: 522]
interoperability/algohosting.md:31:121 MD013/line-length Line length [Expected: 120; Actual: 522]
interoperability/algohosting.md:32:121 MD013/line-length Line length [Expected: 120; Actual: 522]
interoperability/algohosting.md:33:121 MD013/line-length Line length [Expected: 120; Actual: 524]
interoperability/algohosting.md:34:121 MD013/line-length Line length [Expected: 120; Actual: 522]
interoperability/algohosting.md:36:121 MD013/line-length Line length [Expected: 120; Actual: 522]
interoperability/algohosting.md:38:121 MD013/line-length Line length [Expected: 120; Actual: 522]
interoperability/algohosting.md:40:121 MD013/line-length Line length [Expected: 120; Actual: 522]
interoperability/algohosting.md:42:121 MD013/line-length Line length [Expected: 120; Actual: 524]
interoperability/algohosting.md:44:121 MD013/line-length Line length [Expected: 120; Actual: 522]
interoperability/algohosting.md:46:121 MD013/line-length Line length [Expected: 120; Actual: 522]
interoperability/algohosting.md:48:121 MD013/line-length Line length [Expected: 120; Actual: 522]
interoperability/algohosting.md:50:121 MD013/line-length Line length [Expected: 120; Actual: 522]
interoperability/algohosting.md:52:121 MD013/line-length Line length [Expected: 120; Actual: 522]
interoperability/algohosting.md:54:121 MD013/line-length Line length [Expected: 120; Actual: 522]
interoperability/algohosting.md:56:121 MD013/line-length Line length [Expected: 120; Actual: 522]
interoperability/algohosting.md:58:121 MD013/line-length Line length [Expected: 120; Actual: 522]
interoperability/algohosting.md:64:121 MD013/line-length Line length [Expected: 120; Actual: 124]
propagation/enhancement.md:31 MD001/heading-increment Heading levels should only increment by one level at a time [Expected: h2; Actual: h4]
eo_service_usage.qmd:9 MD025/single-title/single-h1 Multiple top-level headings in the same document [Context: "Under construction"]
eo_service_usage.qmd:14 MD025/single-title/single-h1 Multiple top-level headings in the same document [Context: "Python service discovery"]
eo_service_usage.qmd:47 MD025/single-title/single-h1 Multiple top-level headings in the same document [Context: "openEO services"]
eo_service_usage/openeo_usage.md:8:121 MD013/line-length Line length [Expected: 120; Actual: 195]
eo_service_usage/openeo_usage.md:10:121 MD013/line-length Line length [Expected: 120; Actual: 186]
eo_service_usage/openeo_usage.md:17:121 MD013/line-length Line length [Expected: 120; Actual: 129]
eo_service_usage/openeo_usage.md:31:121 MD013/line-length Line length [Expected: 120; Actual: 186]
eo_service_usage/openeo_usage.md:44:121 MD013/line-length Line length [Expected: 120; Actual: 130]
eo_service_usage/openeo_usage.md:49:121 MD013/line-length Line length [Expected: 120; Actual: 199]
eo_service_usage/openeo_usage.md:105:121 MD013/line-length Line length [Expected: 120; Actual: 139]
eo_service_usage/openeo_usage.md:115:121 MD013/line-length Line length [Expected: 120; Actual: 214]
propagation.md:3:121 MD013/line-length Line length [Expected: 120; Actual: 143]
propagation.md:9:121 MD013/line-length Line length [Expected: 120; Actual: 131]
propagation.md:38:121 MD013/line-length Line length [Expected: 120; Actual: 130]
propagation.md:39:121 MD013/line-length Line length [Expected: 120; Actual: 158]
propagation.md:44:121 MD013/line-length Line length [Expected: 120; Actual: 137]
propagation.md:89:121 MD013/line-length Line length [Expected: 120; Actual: 156]
propagation.md:98:121 MD013/line-length Line length [Expected: 120; Actual: 129]
propagation.md:99:121 MD013/line-length Line length [Expected: 120; Actual: 125]
propagation.md:110:121 MD013/line-length Line length [Expected: 120; Actual: 142]
propagation.md:110:5 MD033/no-inline-html Inline HTML [Element: br]
propagation.md:112:3 MD033/no-inline-html Inline HTML [Element: br]
propagation.md:114:3 MD033/no-inline-html Inline HTML [Element: br]
propagation.md:116:3 MD033/no-inline-html Inline HTML [Element: br]
propagation.md:118:3 MD033/no-inline-html Inline HTML [Element: br]
README.md:4:121 MD013/line-length Line length [Expected: 120; Actual: 130]
README.md:25:121 MD013/line-length Line length [Expected: 120; Actual: 131]
README.md:48 MD046/code-block-style Code block style [Expected: fenced; Actual: indented]
interoperability/businessmodel.md:12:121 MD013/line-length Line length [Expected: 120; Actual: 328]
interoperability/businessmodel.md:14:121 MD013/line-length Line length [Expected: 120; Actual: 328]
interoperability/businessmodel.md:16:121 MD013/line-length Line length [Expected: 120; Actual: 328]
interoperability/dashboards.md:3:121 MD013/line-length Line length [Expected: 120; Actual: 224]
interoperability/dashboards.md:5:121 MD013/line-length Line length [Expected: 120; Actual: 370]
interoperability/dashboards.md:7:121 MD013/line-length Line length [Expected: 120; Actual: 248]
interoperability/dashboards.md:9:121 MD013/line-length Line length [Expected: 120; Actual: 346]
interoperability/dashboards.md:25:121 MD013/line-length Line length [Expected: 120; Actual: 291]
interoperability/dashboards.md:34:121 MD013/line-length Line length [Expected: 120; Actual: 203]
interoperability/dashboards.md:43:121 MD013/line-length Line length [Expected: 120; Actual: 144]
interoperability/dashboards.md:46 MD040/fenced-code-language Fenced code blocks should have a language specified [Context: "```"]
index.qmd:7:121 MD013/line-length Line length [Expected: 120; Actual: 166]
index.qmd:21:121 MD013/line-length Line length [Expected: 120; Actual: 203]
index.qmd:22:121 MD013/line-length Line length [Expected: 120; Actual: 158]
index.qmd:26:121 MD013/line-length Line length [Expected: 120; Actual: 172]
index.qmd:27:121 MD013/line-length Line length [Expected: 120; Actual: 176]
index.qmd:29:121 MD013/line-length Line length [Expected: 120; Actual: 135]
interoperability/index.md:14:3 MD033/no-inline-html Inline HTML [Element: br]
interoperability/index.md:16:3 MD033/no-inline-html Inline HTML [Element: br]
interoperability/index.md:18:3 MD033/no-inline-html Inline HTML [Element: br]
propagation/toolboxcloud.md:27 MD001/heading-increment Heading levels should only increment by one level at a time [Expected: h2; Actual: h4]
udp_writer_guide.qmd:1 MD041/first-line-heading/first-line-h1 First line in a file should be a top-level heading [Context: "## Guide for writing openEO Us..."]
udp_writer_guide.qmd:18:121 MD013/line-length Line length [Expected: 120; Actual: 279]
udp_writer_guide.qmd:22:121 MD013/line-length Line length [Expected: 120; Actual: 129]
udp_writer_guide.qmd:23:121 MD013/line-length Line length [Expected: 120; Actual: 129]
udp_writer_guide.qmd:40:121 MD013/line-length Line length [Expected: 120; Actual: 158]
udp_writer_guide.qmd:54:121 MD013/line-length Line length [Expected: 120; Actual: 132]
udp_writer_guide.qmd:69:121 MD013/line-length Line length [Expected: 120; Actual: 126]
udp_writer_guide.qmd:73:121 MD013/line-length Line length [Expected: 120; Actual: 135]
udp_writer_guide.qmd:74:121 MD013/line-length Line length [Expected: 120; Actual: 222]
udp_writer_guide.qmd:76:121 MD013/line-length Line length [Expected: 120; Actual: 162]
udp_writer_guide.qmd:77:121 MD013/line-length Line length [Expected: 120; Actual: 178]
udp_writer_guide.qmd:79:121 MD013/line-length Line length [Expected: 120; Actual: 153]
udp_writer_guide.qmd:101:121 MD013/line-length Line length [Expected: 120; Actual: 209]
udp_writer_guide.qmd:222:121 MD013/line-length Line length [Expected: 120; Actual: 140]
udp_writer_guide.qmd:228:121 MD013/line-length Line length [Expected: 120; Actual: 133]
udp_writer_guide.qmd:265:121 MD013/line-length Line length [Expected: 120; Actual: 139]
udp_writer_guide.qmd:311 MD040/fenced-code-language Fenced code blocks should have a language specified [Context: "```"]
instantiation/documentation.qmd:6:121 MD013/line-length Line length [Expected: 120; Actual: 152]
instantiation/documentation.qmd:8:121 MD013/line-length Line length [Expected: 120; Actual: 139]
instantiation/documentation.qmd:12:121 MD013/line-length Line length [Expected: 120; Actual: 167]
instantiation/documentation.qmd:34:121 MD013/line-length Line length [Expected: 120; Actual: 125]
interoperability/algohostingenv.md:10:121 MD013/line-length Line length [Expected: 120; Actual: 294]
interoperability/algohostingenv.md:11:121 MD013/line-length Line length [Expected: 120; Actual: 152]
interoperability/algohostingenv.md:13:121 MD013/line-length Line length [Expected: 120; Actual: 160]
interoperability/algohostingenv.md:16:121 MD013/line-length Line length [Expected: 120; Actual: 530]
interoperability/algohostingenv.md:18:121 MD013/line-length Line length [Expected: 120; Actual: 530]
interoperability/algohostingenv.md:20:121 MD013/line-length Line length [Expected: 120; Actual: 530]
interoperability/algohostingenv.md:22:121 MD013/line-length Line length [Expected: 120; Actual: 530]
interoperability/algohostingenv.md:23:121 MD013/line-length Line length [Expected: 120; Actual: 530]
interoperability/algohostingenv.md:24:121 MD013/line-length Line length [Expected: 120; Actual: 530]
interoperability/algohostingenv.md:25:121 MD013/line-length Line length [Expected: 120; Actual: 530]
interoperability/algohostingenv.md:26:121 MD013/line-length Line length [Expected: 120; Actual: 530]
interoperability/algohostingenv.md:27:121 MD013/line-length Line length [Expected: 120; Actual: 530]
interoperability/algohostingenv.md:29:121 MD013/line-length Line length [Expected: 120; Actual: 530]
interoperability/algohostingenv.md:31:121 MD013/line-length Line length [Expected: 120; Actual: 530]
interoperability/algohostingenv.md:33:121 MD013/line-length Line length [Expected: 120; Actual: 530]
interoperability/algohostingenv.md:35:121 MD013/line-length Line length [Expected: 120; Actual: 530]
propagation/upscaling.md:7:121 MD013/line-length Line length [Expected: 120; Actual: 129]
propagation/upscaling.md:10:121 MD013/line-length Line length [Expected: 120; Actual: 154]
propagation/upscaling.md:14 MD025/single-title/single-h1 Multiple top-level headings in the same document [Context: "Work in progress"]
propagation/upscaling.md:30:121 MD013/line-length Line length [Expected: 120; Actual: 156]
propagation/upscaling.md:31:121 MD013/line-length Line length [Expected: 120; Actual: 206]
propagation/upscaling.md:32:121 MD013/line-length Line length [Expected: 120; Actual: 184]
propagation/upscaling.md:33:121 MD013/line-length Line length [Expected: 120; Actual: 158]
propagation/upscaling.md:40 MD025/single-title/single-h1 Multiple top-level headings in the same document [Context: "Contact us"]
udp_description_template.md:6 MD025/single-title/single-h1 Multiple top-level headings in the same document [Context: "Performance characteristics"]
udp_description_template.md:12 MD025/single-title/single-h1 Multiple top-level headings in the same document [Context: "Examples"]
udp_description_template.md:17 MD025/single-title/single-h1 Multiple top-level headings in the same document [Context: "Literature references"]
udp_description_template.md:21 MD025/single-title/single-h1 Multiple top-level headings in the same document [Context: "Known limitations"]
udp_description_template.md:29 MD025/single-title/single-h1 Multiple top-level headings in the same document [Context: "Known artifacts"]
instantiation/catalog.qmd:6:121 MD013/line-length Line length [Expected: 120; Actual: 147]
instantiation/catalog.qmd:8:121 MD013/line-length Line length [Expected: 120; Actual: 132]
instantiation/catalog.qmd:54:121 MD013/line-length Line length [Expected: 120; Actual: 127]
instantiation/catalog.qmd:60:121 MD013/line-length Line length [Expected: 120; Actual: 130]
interoperability/references.md:3:121 MD013/line-length Line length [Expected: 120; Actual: 312]
propagation/intercomparison.md:7:121 MD013/line-length Line length [Expected: 120; Actual: 158]
propagation/intercomparison.md:25:121 MD013/line-length Line length [Expected: 120; Actual: 158]

Markdown Link Check......................................................Failed
- hook id: markdown-link-check
- exit code: 1

(node:31489) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)

FILE: propagation/enhancement.md
  [✓] ./hosting.md → Status: 200
  [✓] ./toolboxcloud.md → Status: 200

  2 links checked.

FILE: interoperability/algohosting.md
  [✓] ../propagation.md → Status: 200
  [✓] https://api.openeo.org/ → Status: 200
  [✓] https://semver.org → Status: 200

  3 links checked.

FILE: interoperability/_introduction.md
  No hyperlinks found!

  0 links checked.

FILE: instantiation.md
  [✓] ./instantiation/catalog.qmd → Status: 200
  [✓] ./instantiation/documentation.qmd → Status: 200

  2 links checked.
(node:31486) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)

FILE: propagation.md
  [✓] https://earthcode.esa.int/ → Status: 200
  [✓] interoperability/algohosting.md → Status: 200
  [✖] https://nor-discover.org/en/portfolio/ → Status: 0 Error: unable to verify the first certificate
    at TLSSocket.onConnectSecure (node:_tls_wrap:1679:34)
    at TLSSocket.emit (node:events:519:28)
    at TLSSocket._finishInit (node:_tls_wrap:1078:8)
    at ssl.onhandshakedone (node:_tls_wrap:864:12) {
  code: 'UNABLE_TO_VERIFY_LEAF_SIGNATURE'
}
  [✓] interoperability/algohostingenv.md → Status: 200
  [✓] https://openeo.org/ → Status: 200
  [✓] https://documentation.dataspace.copernicus.eu/notebook-samples/openeo/UDP.html → Status: 200
  [✖] udp_writer_guide.md#sec-udp-writing → Status: 400 [Error: ENOENT: no such file or directory, access '/home/lippenss/src/APEx/apex_documentation/udp_writer_guide.md'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'access',
  path: '/home/lippenss/src/APEx/apex_documentation/udp_writer_guide.md'
}
  [✖] udp_writer_guide.md#sec-udp-integration → Status: 400 [Error: ENOENT: no such file or directory, access '/home/lippenss/src/APEx/apex_documentation/udp_writer_guide.md'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'access',
  path: '/home/lippenss/src/APEx/apex_documentation/udp_writer_guide.md'
}
  [✓] https://open-eo.github.io/openeo-python-client/udp.html#user-defined-processes → Status: 200
  [✓] https://github.com/Open-EO/openeo-community-examples/blob/main/python/Sentinel1_Stats/Sentinel1_Stats.ipynb → Status: 200
  [✓] https://api.openeo.org/#tag/User-Defined-Processes → Status: 200
  [✓] https://terradue.github.io/ogc-eo-application-package-hands-on/ → Status: 200
  [✓] https://openeo.cloud → Status: 200
  [✓] https://dataspace.copernicus.eu → Status: 200
  [✓] https://ellip.terradue.com → Status: 200
  [✖] https://nor-discover.org/ → Status: 0 Error: unable to verify the first certificate
    at TLSSocket.onConnectSecure (node:_tls_wrap:1679:34)
    at TLSSocket.emit (node:events:519:28)
    at TLSSocket._finishInit (node:_tls_wrap:1078:8)
    at ssl.onhandshakedone (node:_tls_wrap:864:12) {
  code: 'UNABLE_TO_VERIFY_LEAF_SIGNATURE'
}
  [✓] propagation/hosting.md → Status: 200
  [✓] propagation/upscaling.md → Status: 200
  [✓] propagation/enhancement.md → Status: 200
  [✓] propagation/toolboxcloud.md → Status: 200
  [✓] propagation/intercomparison.md → Status: 200

  21 links checked.

  ERROR: 4 dead links found!
  [✖] https://nor-discover.org/en/portfolio/ → Status: 0
  [✖] udp_writer_guide.md#sec-udp-writing → Status: 400
  [✖] udp_writer_guide.md#sec-udp-integration → Status: 400
  [✖] https://nor-discover.org/ → Status: 0

FILE: eo_service_usage.qmd
  [✓] https://github.com/ESA-APEx/apex_algorithms/tree/main/algorithm_catalog → Status: 200
  [✓] eo_service_usage/openeo_usage.md → Status: 200

  2 links checked.

FILE: README.md
  [✓] https://quarto.org/ → Status: 200
  [✓] https://pre-commit.com/ → Status: 200
  [✓] https://pipx.pypa.io → Status: 200

  3 links checked.

FILE: eo_service_usage/openeo_usage.md
  [✖] https://openeEO.org → Status: 0 Error: getaddrinfo ENOTFOUND openeeo.org
    at GetAddrInfoReqWrap.onlookupall [as oncomplete] (node:dns:120:26) {
  errno: -3008,
  code: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: 'openeeo.org'
}
  [✓] ../interoperability/algohostingenv.md → Status: 200
  [✓] https://openeofed.dataspace.copernicus.eu → Status: 200
  [✓] https://openeo.cloud → Status: 200
  [✓] https://editor.openeo.cloud → Status: 200
  [✓] https://openeo.org/documentation/1.0/#introduction → Status: 200
  [✓] https://openeo.org/documentation/1.0/javascript/ → Status: 200
  [✓] https://openeo.org/documentation/1.0/python/ → Status: 200
  [✓] https://openeo.org/documentation/1.0/r/ → Status: 200
  [✓] https://open-eo.github.io/openeo-python-client/datacube_construction.html#datacube-from-process → Status: 200
  [✓] https://github.com/Open-EO/openeo-python-client/tree/master/examples → Status: 200
  [✓] https://openeo.org/documentation/1.0/developers/api/reference.html → Status: 200

  12 links checked.

  ERROR: 1 dead links found!
  [✖] https://openeEO.org → Status: 0
(node:31488) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)

FILE: interoperability/dashboards.md
  No hyperlinks found!

  0 links checked.

FILE: interoperability/definitions.md
  [✓] ../interoperability/images/apex_definitions_actors.png → Status: 200

  1 links checked.

FILE: deliverables/d09-icg.md
  No hyperlinks found!

  0 links checked.

FILE: interoperability/businessmodel.md
  No hyperlinks found!

  0 links checked.
(node:31485) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)

FILE: propagation/toolboxcloud.md
  [✓] ./hosting.md → Status: 200
  [✓] ./enhancement.md → Status: 200

  2 links checked.

FILE: udp_writer_guide.qmd
  [✓] https://open-eo.github.io/openeo-python-client/udp.html → Status: 200
  [✓] propagation/enhancement.md → Status: 200
  [✓] https://github.com/ESA-APEx/apex_algorithms/tree/main/openeo_udp/examples/max_ndvi_composite → Status: 200
  [✓] https://github.com/ESA-APEx/apex_algorithms/blob/main/algorithm_catalog/max_ndvi_composite_files/max_ndvi_composite_description.md → Status: 200
  [✓] https://github.com/ESA-APEx/apex_documentation/issues → Status: 200
  [✓] https://github.com/ESA-APEx/apex_documentation/blob/main/udp_description_template.md → Status: 200
  [✓] https://github.com/ESA-APEx/apex_algorithms → Status: 200
  [✓] https://data.esa.int/esado → Status: 200
  [✓] https://spdx.org/licenses/ → Status: 200
  [✓] https://github.com/ESA-APEx/apex_algorithms/tree/main/benchmark_scenarios → Status: 200
  [✓] https://github.com/ESA-APEx/apex_algorithms/blob/main/schema/benchmark_scenario.json → Status: 200
  [✓] https://github.com/Open-EO/openeo-api/tree/draft/extensions/remote-process-definition → Status: 200
  [✓] https://github.com/ESA-APEx/apex_algorithms/actions/workflows/benchmarks.yaml → Status: 200

  13 links checked.

FILE: interoperability/index.md
  [✖] interoperability/algohosting.md → Status: 400 [Error: ENOENT: no such file or directory, access '/home/lippenss/src/APEx/apex_documentation/interoperability/interoperability/algohosting.md'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'access',
  path: '/home/lippenss/src/APEx/apex_documentation/interoperability/interoperability/algohosting.md'
}
  [✖] interoperability/algohostingenv.md → Status: 400 [Error: ENOENT: no such file or directory, access '/home/lippenss/src/APEx/apex_documentation/interoperability/interoperability/algohostingenv.md'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'access',
  path: '/home/lippenss/src/APEx/apex_documentation/interoperability/interoperability/algohostingenv.md'
}
  [✖] interoperability/dashboards.md → Status: 400 [Error: ENOENT: no such file or directory, access '/home/lippenss/src/APEx/apex_documentation/interoperability/interoperability/dashboards.md'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'access',
  path: '/home/lippenss/src/APEx/apex_documentation/interoperability/interoperability/dashboards.md'
}

  3 links checked.

  ERROR: 3 dead links found!
  [✖] interoperability/algohosting.md → Status: 400
  [✖] interoperability/algohostingenv.md → Status: 400
  [✖] interoperability/dashboards.md → Status: 400

FILE: index.qmd
  [✖] ./eo_service_usage.md → Status: 400 [Error: ENOENT: no such file or directory, access '/home/lippenss/src/APEx/apex_documentation/eo_service_usage.md'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'access',
  path: '/home/lippenss/src/APEx/apex_documentation/eo_service_usage.md'
}
  [✓] ./propagation.md → Status: 200

  2 links checked.

  ERROR: 1 dead links found!
  [✖] ./eo_service_usage.md → Status: 400
(node:31487) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)

FILE: instantiation/documentation.qmd
  [✓] https://quarto.org/ → Status: 200

  1 links checked.

FILE: udp_description_template.md
  No hyperlinks found!

  0 links checked.

FILE: propagation/upscaling.md
  [✓] ./hosting.md → Status: 200
  [✓] ./enhancement.md → Status: 200
  [✓] https://docs.openeo.cloud/usecases/large-scale-processing/ → Status: 200
  [✓] https://documentation.dataspace.copernicus.eu/APIs/openEO/large_scale_processing.html → Status: 200
  [✓] https://github.com/Open-EO/openeo-community-examples/blob/main/python/ManagingMultipleLargeScaleJobs/ManagingMultipleLargeScaleJobs.ipynb → Status: 200

  5 links checked.

FILE: interoperability/algohostingenv.md
  [✓] https://api.openeo.org/#tag/User-Defined-Processes → Status: 200
  [✓] https://openeo.org/documentation/1.0/developers/profiles/api.html#l1b-minimal-batch-jobs → Status: 200
  [✓] https://github.com/Open-EO/openeo-api/tree/draft/extensions/remote-process-definition → Status: 200
  [✓] https://docs.ogc.org/bp/20-089r1.html → Status: 200
  [✓] https://www.commonwl.org/ → Status: 200
  [✓] https://eoepca.org → Status: 200

  6 links checked.
(node:31490) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)

FILE: instantiation/catalog.qmd
  [✓] https://stacspec.org/en → Status: 200
  [✓] https://radiantearth.github.io/stac-browser/#/?.language=en → Status: 200
  [✓] https://github.com/stac-utils/stac-fastapi-elasticsearch-opensearch → Status: 200

  3 links checked.

FILE: propagation/intercomparison.md
  [✓] ./toolboxcloud.md → Status: 200
  [✓] ./enhancement.md → Status: 200

  2 links checked.

FILE: interoperability/references.md
  [✓] https://docs.ogc.org/is/18-062r2/18-062r2.html → Status: 200
  [✓] https://w3id.org/cwl/ → Status: 200
  [✓] https://stacspec.org → Status: 200
  [✓] https://github.com/stac-extensions/projection → Status: 200
  [✓] https://docs.ogc.org/bp/20-089r1.html → Status: 200
  [✓] https://openeo.org/documentation/1.0/developers/api/reference.html → Status: 200
  [✓] https://openeo.org/documentation/1.0/developers/profiles/api.html → Status: 200
  [✓] https://openeo.org/documentation/1.0/developers/profiles/processes.html → Status: 200
  [✓] https://docs.ogc.org/is/21-026/21-026.html → Status: 200
  [✓] https://www.ogc.org/standard/netcdf/ → Status: 200

  10 links checked.

FILE: propagation/hosting.md
  [✓] https://esa-sef.eu/ → Status: 200
  [✓] #execute-a-service-from-the-apex-algorithm-catalogue → Status: 200
  [✓] ../interoperability/algohosting.md → Status: 200
  [✖] https://portfolio.nor-discover.org/ → Status: 0 Error: unable to verify the first certificate
    at TLSSocket.onConnectSecure (node:_tls_wrap:1679:34)
    at TLSSocket.emit (node:events:519:28)
    at TLSSocket._finishInit (node:_tls_wrap:1078:8)
    at ssl.onhandshakedone (node:_tls_wrap:864:12) {
  code: 'UNABLE_TO_VERIFY_LEAF_SIGNATURE'
}
  [✓] ./upscaling.md → Status: 200

  5 links checked.

  ERROR: 1 dead links found!
  [✖] https://portfolio.nor-discover.org/ → Status: 0

```

**Comment by soxofaan** [comment]
I would first try to get that markdown-link-check integrated, which adds most value I think,

The other one, markdownlint-cli, will be probably be more work

**Comment by JanssenBrm** [comment]
Great, thanks for the feedback @soxofaan! It is great to see that it is working properly. As there is quite a lof of editing ongoing in the document, I'm going to remove the markdownlint-cli for now and create a new issue for this. We can do this after the SRR milestone.

**Pull request merged**
